---
  - hosts: all
    become: true
    tasks:
      - name: Dump Morpheus Dict Full
        debug:
          msg: "{{ morpheus }}"
        ignore_errors: true
      - name: Dump Morpheus Dict Instance
        debug:
          msg: "{{ morpheus['instance'] }}"
        ignore_errors: true

      - name: Dump Morpheus Main Container
        debug:
          msg: "{{ morpheus['instance']['apps'][0]['instances'][0]['container']['internalIp'] }}"
        ignore_errors: true
      - name: Dump Morpheus Main Container 2
        debug:
          msg: "{{ morpheus['instance']['apps'][0]['instances'][0]['containers'][0]['server']['internalIp'] }}"
        ignore_errors: true

      - name: Dump Morpheus Filter
        debug:
          msg: "{% for instance in morpheus['instance']['apps'][0]['instances'] if 'DB' in instance.displayName %}{{ instances['container']['internalIp'] }}{% endfor %}"
        ignore_errors: true